# Generated by Django 5.2.8 on 2025-11-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Dish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DishRestaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.restaurant')),
            ],
            options={
                'db_table': 'DishRestaurant',
                'managed': True,
            },
        ),
    ]
