# Generated by Django 5.2.8 on 2025-11-26 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrestaurant',
            name='dish',
            field=models.ForeignKey(db_column='dish_id', on_delete=django.db.models.deletion.CASCADE, to='Menu.dish'),
        ),
        migrations.AlterField(
            model_name='dishrestaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dishrestaurant',
            name='restaurant',
            field=models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='Menu.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='dishrestaurant',
            unique_together={('dish', 'restaurant')},
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dbo_Menu',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='dbo_Restaurant',
        ),
    ]
