# Generated by Django 5.2.8 on 2025-11-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_dishrestaurant_dish_alter_dishrestaurant_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dish',
            table='dbo.Menu',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='dbo.Restaurant',
        ),
    ]
